#!/bin/bash

script=$1

if [ ! $script ]
then
echo "Provide a script!"
echo "script-to-path <script>"
exit 1
fi

if [ ! -e $script ]
then
echo "$script was not found!"
exit 1
fi

if [ ! $PATH =~ "/usr/local/scripts" ]
then
export PATH=/usr/local/scripts:$PATH
fi

if [ ! -e "/usr/local/scripts" ]
then
sudo mkdir /usr/local/scripts
fi



sudo cp $script /usr/local/scripts/$script
sudo chmod +x /usr/local/scripts/$script

echo "$script added to path!"