#!/bin/bash

script=$1

if [ ! $script ]
then
echo "Provide a script!"
echo "script-to-path <script>"
exit 1
fi

if [ ! -e $script ]
then
echo "$script was not found!"
exit 1
fi

cd ~

if [ ! -e ".scritps" ]
then
echo does not exist
mkdir .scripts
fi

cp -r $script .scripts/$script
chmod +x .scripts/$script

cd -

echo "$script added to path!"