#!/bin/bash

script=$1

if [ ! $script ]
then
echo "Provide a script!"
echo "script-to-path <script>"
exit 1
fi

if [ ! -e $script ]
then
echo "$script was not found!"
exit 1
fi

cd ~

if [ ! -d ".scripts" ]
then
mkdir .scripts
fi

if [ -e ".scripts/$script" ]
then
echo "$script already in path!"
exit 1
fi

cd -
cp $script .scripts
chmod +x .scripts/$script

echo "$script added to path!"